"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ASSOCIATIVITY_RIGHT = exports.ASSOCIATIVITY_LEFT = exports.BRACKET_RIGHT = exports.BRACKET_LEFT = exports.DIVISION = exports.MULTIPLICATION = exports.SUBTRACTION = exports.ADDITION = void 0;
exports.ADDITION = '+';
exports.SUBTRACTION = '-';
exports.MULTIPLICATION = '*';
exports.DIVISION = '/';
exports.BRACKET_LEFT = '(';
exports.BRACKET_RIGHT = ')';
exports.ASSOCIATIVITY_LEFT = 'left';
exports.ASSOCIATIVITY_RIGHT = 'right';
